logging:
  level:
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG

spring:
  datasource:
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5444/postgres
     username: postgres
     password: realworldpassword

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # for read (where in clause)
        default_batch_fetch_size: 100

        # for write (batch insert)
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 10

security:
  key:
    private: classpath:app.key
    public: classpath:app.pub

decorator:
  datasource:
    p6spy:
      enable-logging: true
