logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG

security:
  key:
    private: classpath:app.key
    public: classpath:app.pub

spring:
  datasource:
    url: jdbc:h2:mem:testdb?MODE=MYSQL;

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop

decorator:
  datasource:
    p6spy:
      enable-logging: true
