logging:
  level:
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb?MODE=MYSQL
    username: sa
    hikari:
      max-lifetime: 120_000 # ms
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        # for read (where in clause)
        default_batch_fetch_size: 100

        # for write (batch insert)
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 10

security:
  key:
    private: classpath:app.key
    public: classpath:app.pub

decorator:
  datasource:
    p6spy:
      enable-logging: true
