create table article
(
    id          integer generated by default as identity,
    created_at  timestamp(6)  not null,
    updated_at  timestamp(6),
    author_id   uuid          not null,
    description varchar(50)   not null,
    slug        varchar(50)   not null unique,
    title       varchar(50)   not null unique,
    content     varchar(1000) not null,
    primary key (id)
);

create table article_favorite
(
    article_id integer,
    id         integer generated by default as identity,
    created_at timestamp(6) not null,
    user_id    uuid,
    primary key (id),
    constraint ukpatixq7onikvvq0vw8cg039fu unique (user_id, article_id)
);

create table article_tag
(
    article_id integer,
    id         integer generated by default as identity,
    created_at timestamp(6) not null,
    tag_name   varchar(20),
    primary key (id),
    constraint uk6mf7aqqemxogkbdi5j1407ehg unique (article_id, tag_name)
);

create table article_comment
(
    article_id integer      not null,
    id         integer generated by default as identity,
    created_at timestamp(6) not null,
    author_id  uuid         not null,
    content    varchar(500) not null,
    primary key (id)
);

create table tag
(
    created_at timestamp(6) not null,
    name       varchar(20)  not null,
    primary key (name)
);

create table user_follow
(
    id           integer generated by default as identity,
    created_at   timestamp(6) not null,
    follower_id  uuid,
    following_id uuid,
    primary key (id),
    constraint ukp8vhuhxu2u1fm8qg7hvn4y1gs unique (follower_id, following_id)
);

create table users
(
    created_at timestamp(6) not null,
    id         uuid         not null,
    email      varchar(30)  not null unique,
    username   varchar(30)  not null unique,
    image_url  varchar(200),
    password   varchar(200) not null,
    bio        varchar(500),
    primary key (id)
);

alter table if exists article
    add constraint fkmjgtny2i22jf4dqncmd436s0u foreign key (author_id) references users;

alter table if exists article_favorite
    add constraint fkb8vit5sr2sivwocuy4qxatn8c foreign key (article_id) references article;

alter table if exists article_favorite
    add constraint fk8m1q6r31lmkejfp8l8eka6n93 foreign key (user_id) references users;

alter table if exists article_tag
    add constraint fkenqeees0y8hkm7x1p1ittuuye foreign key (article_id) references article;

alter table if exists article_tag
    add constraint fk27dk3xr3kdb606oobk5yn7m1c foreign key (tag_name) references tag;

alter table if exists article_comment
    add constraint fkghmocqkgqs5tkmucf5putw64t foreign key (article_id) references article;

alter table if exists article_comment
    add constraint fkr6n3iwt28icgmsn2bnargxqd1 foreign key (author_id) references users;

alter table if exists user_follow
    add constraint fki9gqdjcgtclgypxp2krye61n7 foreign key (follower_id) references users;

alter table if exists user_follow
    add constraint fk474orxbed564dk0mvggvt4xon foreign key (following_id) references users;